name: "Pretty-Printed Changelogs on PRs"
description: 'Creates a pretty-printed changelog from the commits of a Pull Request, and adds them to the body of that pull request.' 
author: 'Emily Dixon'
branding:
  color: green
  icon: align-left

inputs:
  pull_number:
    description: "The number of the PR to generate notes for. You only need to specify this if you're calling from an event other than pull_request"
    required: true
    default: ${{ github.event.pull_request.number }}
  token:
    description: "A GITHUB_TOKEN or Personal Access Token that is scoped to allow editing pull requests"
    required: true
  labels:
    description: "A comma-delimited list of labels that should be used as headings. If none are provided, changes will be labeled as 'Improvements'"
    required: false
    default: ""
  titles:
    description: "A comma-delimited list of custom titles that match the labels. These titles will be used as headings for their respective labels"
    required: false
    default: ""
  filters:
    description: 'A comma-delimited list of labels that should be filtered out before adding commit messages to the changelog'
    required: false
    default: ""
runs:
  using: 'node16'
  main: 'notes.js'
