on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Warn them
        run: echo "WARNING! You have to manually set which branch to test. If you don't, you'll be testing main. Sorry about that"
      - name: Generate some release notes
        id: notes
        # You have to update this with your branch when developing. 
        #   It doesn't look like you can use env, steps, or github contexts
        #   for a uses:
        uses: sanketnaik99/changelog-on-pr@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: breaking,fixes
          titles: Fixes 🔧,Breaking Changes
          filters: MKT - ,WFM - ,
      - name: Just echo something
        run: echo "Anything "
